version: '3.4'

services:
  respobot:
    image: ${DOCKER_REGISTRY-}respobot
    build:
      context: .
      dockerfile: RespoBot/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: "development"
      RespoBot:RespoBot:Token: ""
      RespoBot:RespoBot:TestGuildId: ""
      RespoBot:RespoBot:ResultsServiceInterval: ""